name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  autotesting:
    runs-on: ubuntu-latest
    steps:

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'

    - name: Cloning the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    - name: Run tests
      run: |
        ./gradlew test

    - name: Tests succeed
      if: success()
      run: exit 0
    
    - name: Tests failed
      if: failure()
      run: exit 1
      
  code_cleanup:
    needs: autotesting
    runs-on: ubuntu-latest
    steps:

    - name: Cloning the repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        
    - name: Format the Java code
      uses: lwerner-lshigh/prettier_action_java@v1.1.1
      with:
        prettier_options: '--no-semi --use-tabs --no-bracket-spacing --end-of-line lf --bracket-same-line --write **/*.java'
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  notification:
    needs: code_cleanup
    runs-on: ubuntu-latest
    steps:
      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_SECRET }}
          SLACK_USERNAME: Updates Notifier
          SLACK_TITLE: Some updates in main repository